### ISSUE TITLE
Loading other dependencies mentioned in plugin pom

### ISSUE THREAD

**Issue by hokutor** [pf4j/pf4j#461] opened 2021-07-06 01:00 UTC
Hello Team

I was wondering if the dependencies mentioned in the pom file of a plugin also gets loaded when plugin is started? Apparently, I can see the classes are packaged inside the plugin jar upon build but host app isn't able to detect those classes.

Cheers

**Comment by hokutor** [comment] 2021-07-06 01:34
I tried to check with following code

```java
Class.forName("com.huaweicloud.sdk.iam.v3.region.IamRegion");
```

I can see above class is available in the packaged plugin jar. But the statement throws error 

```logs
java.lang.ClassNotFoundException: com.huaweicloud.sdk.iam.v3.region.IamRegion
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
```

Just wanna check if I am missing something. Am using the com.huawei.roma.runtime.core.managers.DefaultPluginManager to load my plugins

**Comment by hokutor** [comment] 2021-07-06 15:33
Could it be packaging issue. My plugin jar root looks like 

![image](https://user-images.githubusercontent.com/81697586/124627905-f0e01f00-de4d-11eb-8b74-9687b8d0ea6f.png)

**Comment by decebals** [comment] 2021-07-06 15:39
> Could it be packaging issue. My plugin jar root looks like
> 
> ![image](https://user-images.githubusercontent.com/81697586/124627905-f0e01f00-de4d-11eb-8b74-9687b8d0ea6f.png)

Yes, I think that is a plugin packaging issue. From what I see your plugin(s) is distributed as a fat JAR. Please check that one ore more classes from the dependency are included in the resulted JAR file. The simple approach is to check the package root (as folder) of dependency in the resulted JAR file.

**Comment by hokutor** [comment] 2021-07-06 15:50
> > Could it be packaging issue. My plugin jar root looks like
> > ![image](https://user-images.githubusercontent.com/81697586/124627905-f0e01f00-de4d-11eb-8b74-9687b8d0ea6f.png)
> 
> Yes, I think that is a plugin packaging issue. From what I see your plugin(s) is distributed as a fat JAR. Please check that one ore more classes from the dependency are included in the resulted JAR file. The simple approach is to check the package root (as folder) of dependency in the resulted JAR file.

Thanks @decebals . Really appreciate your support. As per your advice, I checked the jar and found the class is actually available in the package 

![image](https://user-images.githubusercontent.com/81697586/124630227-37367d80-de50-11eb-8468-d53f5aa652e7.png)

My build plugin looks as follows
```xml
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <finalName>${project.artifactId}-${project.version}-all</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                    <attach>false</attach>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                        </manifest>
                        <manifestEntries>
                            <Plugin-Id>${plugin.id}</Plugin-Id>
                            <Plugin-Version>${plugin.version}</Plugin-Version>
                            <Plugin-Provider>${plugin.provider}</Plugin-Provider>
                            <Plugin-Class>${plugin.class}</Plugin-Class>
                            <Plugin-Dependencies>${plugin.dependencies}</Plugin-Dependencies>
                        </manifestEntries>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```


Am I missing some other settings anywhere?

**Comment by decebals** [comment] 2021-07-07 09:44
> Am I missing some other settings anywhere?

I read the description of this issue again.
If I understand correctly, you try to access in application core a class that is loaded by a plugin and that is not possible. That class is available any in the class loader of the plugin and in all other plugins that declare that plugin as dependency (via plugin descriptor).
 
In your app, when you need to deal with class loader, you can use one of three types of class loaders:
- app's class loader
- plugin's class loader (a plugin's class loader has as parent the app's class loader)
- a compound/uber/global class loader that aggregates all the plugin's class loader 

Maybe you can un https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L690.
Also, read https://github.com/pf4j/pf4j/issues/93#issuecomment-188526528, maybe it's useful for your case.

**Comment by decebals** [comment] 2021-11-13 11:25
@hokutor 

Can you create a simple [quickstart](https://pf4j.org/dev/quickstart.html) application that replicate the problem and to make it public (on ghithub or a git repository in general or attach the zip with the project here)? The idea is to be able to reproduce and debug the problem is isolation.

**Comment by decebals** [comment] 2022-09-17 16:24
@hokutor Can we close this issue? Can I help you with anything else?

**Comment by decebals** [comment] 2023-08-02 23:21
Reopen the issue if you think it is still relevant for you.

**Closed by decebals** 2023-08-02 23:21 UTC
