### ISSUE TITLE
Space in Plugin Path throws Exception

### ISSUE THREAD

**Issue by michooo** [pf4j/pf4j#213] opened 2018-04-16 09:57 UTC
**Windows 10, JRE 8u162**

When the path to the Plugin-Directory contains a space, then the following exception is thrown:

```
org.pf4j.PluginException: No PluginDescriptorFinder for plugin 'G:\eclipse_oxygen\workspace\ServiceApp\plug ins\BalCalculatorPlugin-0.0.1.jar'
	at org.pf4j.CompoundPluginDescriptorFinder.find(CompoundPluginDescriptorFinder.java:78)
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:820)
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:141)
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:227)
	at ch.main.plugins.ScreenControllerPluginService.loadPlugins(ScreenControllerPluginService.java:69)
	at ch.main.ServiceAppMain.start(ServiceAppMain.java:148)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```

When I change Path from `G:\eclipse_oxygen\workspace\ServiceApp\plug ins` to `G:\eclipse_oxygen\workspace\ServiceApp\plugins` all loads fine.

My Main Method:

```
Path pathToPluginsDir = new File("G:\\eclipse_oxygen\\workspace\\ServiceApp\\plug ins\\").toPath();

pluginManager = new DefaultPluginManager(pathToPluginsDir) {
   @Override
   protected CompoundPluginDescriptorFinder createPluginDescriptorFinder() {
      return new CompoundPluginDescriptorFinder().add(new PropertiesPluginDescriptorFinder());
   }
};

// load the plugins
pluginManager.loadPlugins();
```

Any idea?

**Comment by decebals** [comment] 2018-04-16 10:52
I think that is duplicate of #202. The issue is resolved on SNAPSHOT but is nit released yet.

**Comment by decebals** [comment] 2018-04-18 10:01
@michooo 

Instead of 
```
pluginManager = new DefaultPluginManager(pathToPluginsDir) {
   @Override
   protected CompoundPluginDescriptorFinder createPluginDescriptorFinder() {
      return new CompoundPluginDescriptorFinder().add(new PropertiesPluginDescriptorFinder());
   }
};
```

you can use the simple
```
pluginManager = new DefaultPluginManager(pathToPluginsDir) {
   @Override
   protected PluginDescriptorFinder createPluginDescriptorFinder() {
      return new PropertiesPluginDescriptorFinder();
   }
};
```

**Comment by decebals** [comment] 2018-04-28 05:34
@michooo 
Do you have a resolution for this issue? Can we close it?

**Comment by decebals** [comment] 2018-05-03 11:26
I close it because I didn't receive a response. Please opened it if you consider.

**Closed by decebals** 2018-05-03 11:26 UTC
Labels: duplicate
