### ISSUE TITLE
Why is the result of PluginManager.getExtensions empty?

### ISSUE THREAD

**Issue by WolfgangFahl** [pf4j/pf4j#249] opened 2018-11-13 11:55 UTC
https://stackoverflow.com/questions/53280499/why-is-the-result-of-pluginmanager-getextensions-empty

**Comment by decebals** [comment] 2018-11-13 13:08
I think that problem is described well enough in [Troubleshooting](https://pf4j.org/doc/troubleshooting.html) section of documentation.
The **extensions.idx** is created automatically by the annotations processor (you do not have to do anything manually).

Can we close the issue?

PS. I see that I cannot post a response on Stackoverflow:
![image](https://user-images.githubusercontent.com/1248311/48415338-c6e60580-e755-11e8-9fde-e953c00cdc18.png)

I think that I was banned because I tried to comment only posts that involve personal projects .

**Comment by WolfgangFahl** [comment] 2018-11-13 16:53
i would not close the issue but improve the software as well as the documentation. I took me a few hours to get this fixed and it was not what I expected. The idx file is not created in my environment. So currently there is only a workaround and not a fix of this issue. I'd simply put myself in the shoes of a newbie and start from a "clean" maven and eclipse. And in that environment PF4J does not work "out of the box". That will hold up quite a few users in adopting it.

**Comment by WolfgangFahl** [comment] 2018-11-13 16:54
For your stackoverflow issue https://meta.stackoverflow.com/questions/255583/what-can-i-do-when-getting-we-are-no-longer-accepting-questions-answers-from-th might be the point to work from.

**Comment by WolfgangFahl** [comment] 2018-12-04 08:38
Could you please get in touch by e-mail again? I still have trouble getting pf4j working properly and there are bits and pieces all over the issues here that I needed to use to get close to a solution. I think improving the documentation will help a lot.

**Comment by WolfgangFahl** [comment] 2018-12-04 10:06
I downloaded the latest version of pf4j and debugged the issue for another use case of the library. I seem to have done everything the same as in the first use case. This time I didn't try a work-around but used things as described in the documentation
In line 104 of AbstractionFind 
`    if (type.isAssignableFrom(extensionClass)) {
`
fails although a unit test case in the plugin itself:
 
```
  @Test
  public void testPlugin() {
    // test assignability at compile time
    DropHandler handler=new PDFDropHandlerPlugin.PDFDropHandler();
    // test assignability at run time
    Class<? extends DropHandler> pluginType = handler.getClass();
    Class<DropHandler> type = DropHandler.class;
    assertTrue(type.isAssignableFrom(pluginType));
  }
```
works

**Comment by WolfgangFahl** [comment] 2018-12-04 11:05
https://stackoverflow.com/questions/5375349/class-instance-obtained-through-multiple-class-loader
and your own documentation
https://pf4j.org/doc/class-loading.html 
state the issue.
For a "Default" solution I'd expect to work better "out of the box". So having a separate class loader for each instance seems to be a non -default decision to me.

**Comment by decebals** [comment] 2018-12-04 11:12
They are two possible causes for no extensions issue:
1. something is wrong with you IDE (the APT - Annotation Processing Tool - is not configured properly), and from this reason the `extensions.idx` (file that contains all metadata about extensions from a plugin) is missing or is empty
2. a class loader issue (you have the same library/jar loaded with the `ApplicationClassLoader` and `PluginClassLoader`)

The problem is described (maybe is not clear and detailed enough) in the [Troubleshooting](https://pf4j.org/doc/troubleshooting.html) section of documentation. Sure, we can/must improve it (a PR is very welcome at https://github.com/pf4j/pf4j.github.io).

I will list below the solutions (references) for both problems:
1. https://github.com/pf4j/pf4j/issues/21
2. https://github.com/pf4j/pf4j/issues/230, https://github.com/pf4j/pf4j/issues/110, https://github.com/pf4j/pf4j/issues/64, https://github.com/pf4j/pf4j/issues/82

**Comment by WolfgangFahl** [comment] 2018-12-04 11:39
Thank you for getting back so quickly - How come #82 is considered closed? The Troubleshooting section does not really explain or solve the issue.

**Comment by decebals** [comment] 2018-12-04 11:41
> So having a separate class loader for each instance seems to be a non -default decision to me.

A solution is to create a new `SimplePluginManager` that extends `DefaultPluginManager` and that uses a single classloader for all plugins (see the code from https://pf4j.org/doc/class-loading.html).
It's only an idea, I didn't use a such plugin manager in my projects. I am not sure that some features work as expected (load new version of plugin via unload/delete/load/start). Must be tested.

**Comment by decebals** [comment] 2018-12-04 11:44
> How come #82 is considered closed? The Troubleshooting section does not really explain or solve the issue.

It was closed by reporter https://github.com/pf4j/pf4j/issues/82#event-480276554 (was a duplicate).
The only one problem is that the `Troubleshooting` section is not updated.

**Comment by WolfgangFahl** [comment] 2018-12-04 11:45
Thanks for the idea - just tried it out and unfortunately does not work.
```
package com.bitplan.dragtop;

import java.nio.file.Path;

import org.pf4j.DefaultPluginManager;
import org.pf4j.JarPluginLoader;
import org.pf4j.ManifestPluginDescriptorFinder;
import org.pf4j.PluginClassLoader;
import org.pf4j.PluginDescriptor;
import org.pf4j.PluginDescriptorFinder;
import org.pf4j.PluginLoader;
import org.pf4j.PluginManager;
import org.pf4j.RuntimeMode;

/**
 * see https://github.com/pf4j/pf4j/issues/249 see
 * https://pf4j.org/doc/class-loading.html
 * 
 * @author wf
 *
 */
public class WorkAroundPluginManager extends DefaultPluginManager {
  public static class WorkAroundPluginLoader extends JarPluginLoader {
    /**
     * 
     * @param pluginManager
     */
    public WorkAroundPluginLoader(PluginManager pluginManager) {
      super(pluginManager);
    }

    static PluginClassLoader pluginClassLoader;

    @Override
    public ClassLoader loadPlugin(Path pluginPath,
        PluginDescriptor pluginDescriptor) {
      if (pluginClassLoader == null)
        pluginClassLoader = new PluginClassLoader(pluginManager,
            pluginDescriptor, getClass().getClassLoader());
      pluginClassLoader.addFile(pluginPath.toFile());

      return pluginClassLoader;
    }
  }

  public WorkAroundPluginManager() {
    setRuntimeMode(RuntimeMode.DEVELOPMENT);
  }

  @Override
  protected PluginLoader createPluginLoader() {
    // load only jar plugins
    return new WorkAroundPluginLoader(this);
  }

  @Override
  protected PluginDescriptorFinder createPluginDescriptorFinder() {
    // read plugin descriptor from jar's manifest
    return new ManifestPluginDescriptorFinder();
  }


```

**Comment by WolfgangFahl** [comment] 2018-12-04 11:52
#64 is also closed without any improvement - the pom's in the examples use the maven assembly plugin and not the jar plugin - this seems to introduce the problem in the first place since this way the class file for the interface file is now also in the jar file of the plugin.

**Comment by WolfgangFahl** [comment] 2018-12-04 12:11
PluginClassLoader has a line
` if (className.startsWith(PLUGIN_PACKAGE_PREFIX) && !className.startsWith("org.pf4j.demo")) {
`
which seems to fake the demo functionality and has the potential to take any of your unit test ad absurdum.

**Comment by WolfgangFahl** [comment] 2018-12-04 14:34
In line 124 and 125 of PluginClassLoader.java if find:

```
              // use the standard ClassLoader (which follows normal parent delegation)
                return super.loadClass(className);

```
In the example above I am deriving the WorkaroundPluginLoader from JarPluginLoader so I assume super.loadClass will not do what the comment says. One would have to call super.super.loadClass which is not allowed see
https://stackoverflow.com/questions/586363/why-is-super-super-method-not-allowed-in-java

so there needs to be a fix to the Documentation to warn about not deriving mulitple times or change the code to allow for it.

**Comment by WolfgangFahl** [comment] 2018-12-04 14:57
https://github.com/BITPlan/com.bitplan.dragtop/blob/master/src/main/java/com/bitplan/dragtop/JarPluginManager.java

now has a PluginManager that seems to work.
It's instantiated from the class that uses the plugin
`  pluginManager = new JarPluginManager(this.getClass().getClassLoader());
`

**Closed** 2022-07-01 10:19 UTC
