### ISSUE TITLE
Disable Plugin is not working

### ISSUE THREAD

**Issue by MohankumarD** [pf4j/pf4j#261] opened 2018-12-12 13:00 UTC
I have created disabled.txt file in plugins folder and added plugin-id to disable. Its shows me in disable list but is resolved and I am able to access plugin feature. 

c.q.s.SpringcontainerApplication         : Starting SpringcontainerApplication on Qrz-Mohan with PID 10596 
c.q.s.SpringcontainerApplication         : No active profile set, falling back to default profiles: default
org.pf4j.DefaultPluginStatusProvider     : Enabled plugins: []
org.pf4j.DefaultPluginStatusProvider     : **Disabled plugins: [spring-plugin]**
org.pf4j.DefaultPluginManager            : PF4J version 2.3.0 in 'deployment' mode
org.pf4j.CompoundPluginDescriptorFinder  : C:\plugins\springplugin-1.0.0.jar
org.pf4j.AbstractPluginManager           : **Plugin 'plugins\springplugin-1.0.0.jar' is disabled**
org.pf4j.AbstractPluginManager           : **`Plugin 'spring-plugin@1.0.0' resolved`**
org.pf4j.AbstractPluginManager           : Start plugin 'spring-plugin@1.0.0'
**Spring Sample plugin.start()**
o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 9090
c.q.s.SpringcontainerApplication         : Started SpringcontainerApplication in 4.557 seconds (JVM running for 6.795)
**Number of plugins found: 1**

**Comment by decebals** [comment] 2018-12-12 18:01
I released a new version today, 2.5.0, so please test again with this version.

**Comment by MohankumarD** [comment] 2018-12-13 09:47
I am using "pf4j-spring" version "0.5.0". Please let me know which version should I use. See only 2 version in 0.4.0 and 0.5.0

**Comment by decebals** [comment] 2018-12-13 20:11
I tested (`pf4j/demo` and `pf4j-spring/demo`) and I can't reproduce the problem.
Please run `run-demo.sh` script and see if the problem can be reproduced on demo.

**Comment by MohankumarD** [comment] 2018-12-14 05:31
Hi, Thanks for the update. Ya it's fixed once after upgrading to 2.5.0

**Comment by decebals** [comment] 2018-12-14 09:13
I will update PF4J to 2.5.0 and I will release a new version.
Do you need more help? May we close this issue?

**Closed** 2018-12-27 10:46 UTC
