### ISSUE TITLE
Is PF4J and PF4J-Spring compatible with spring boot 3

### ISSUE THREAD

**Issue by charbelsdk** [pf4j/pf4j#589] opened 2024-08-19 07:47 UTC
recently when we updated our project from spring boot 2.5.15 to 3.2.8, the framework is not working correctly.
It's not extracting the plugin zip archive under the plugins directory.
I applied the same example here https://github.com/pf4j/pf4j-spring?tab=readme-ov-file#how-to-use but the list is returning null because it's not being injected

**Comment by charbelsdk** [comment] 2024-08-19 11:52
The issue is with the init method in the SpringPluginManager class.
The method is annotated by javax.annotation.PostConstruct which is deprecated and replaced by jakarta.annotation.PostConstruct.
The SpringPluginManager class is initiated without loading the plugins, thus failing to inject and load the extensions

**Comment by decebals** [comment] 2024-08-25 14:32
Duplicate of https://github.com/pf4j/pf4j-spring/issues/83.

**Closed** 2024-08-25 14:32 UTC
