### ISSUE TITLE
PF4J's version in fat/uber jar

### ISSUE THREAD

**Issue by MacTrophy** [pf4j/pf4j#390] opened 2020-07-29 12:08 UTC
When the project using pf4j is built as a fat/uber jar, pf4j detects the version from the project. I.e. lets say the project is version 1.2.3 and pf4j is 3.5.0-SNAPSHOT it will log

> PF4J version 1.2.3 in 'deployment' mode

instead of expected

> PF4J version 3.5.0-SNAPSHOT in 'deployment' mode

This is because all libraries jar files are merged in the project's jar which results in only one manifest file in the fat/uber jar which is the project's one. Honestly it's not that a big issue as long as the project's developer doesn't need to know what is pf4j's version from the logs.

Alternatives I think of could be for pf4j to use a separate file (a bit similar to the plugin.properties files) i.e. pf4j.properties to fetch the version (and other info?) from such a file instead of the manifest.

I don't know if this is considered something that is pertinent to pf4j, if not feel free to close this issue.

**Comment by decebals** [comment] 2020-07-30 21:24
I understand the problem. To be honest the problem is not critical but I really appreciate you reporting it. Thanks!
We will see. For now, I leave the issue open.

**Comment by decebals** [comment] 2023-07-20 09:48
Fixed by #455

**Closed by decebals** 2023-07-20 09:48 UTC
